name: CI
on: [push, pull_request]

jobs:
  linters:
    if: false  # FIXME
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testenv:
          - pylint
          - flake8
          - mypy
          - docs
          - vulture
          - misc
          - pyroma
          - check-manifest
          - eslint
          - shellcheck
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        if: "matrix.testenv == 'eslint'"
      - name: Set up problem matchers
        run: "python3 scripts/dev/ci/problemmatchers.py ${{ matrix.testenv }}"
      - name: Install dependencies
        run: "bash scripts/dev/ci/install.sh ${{ matrix.testenv }}"
      - name: "Run ${{ matrix.testenv }}"
        run: "bash scripts/dev/ci/run.sh ${{ matrix.testenv }}"

  tests-docker:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - archlinux-webkit
          - archlinux-webengine
          # - archlinux-webengine-unstable
    container:
      image: "qutebrowser/ci:${{ matrix.image }}"
      env:
        QUTE_BDD_WEBENGINE: "${{ matrix.image != 'archlinux-webkit' }}"
        DOCKER: "${{ matrix.image }}"
        CI: true
      options: --privileged --tty --interactive
    steps:
      - uses: actions/checkout@v2
      - run: tox -e py38


  # tests:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       include:
  #         ### PyQt 5.7.1 (Python 3.5)
  #         - os: ubuntu-16.04
