name: Update dependencies

on:
  schedule:
    # Every Monday at 04:05 UTC
    # https://crontab.guru/#05_04_*_*_1
    - cron: '05 04 * * 1'

jobs:
  update:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.1.1
        with:
          python-version: '3.x'
      - name: Recompile requirements
        run: python3 scripts/dev/recompile_requirements.py
        id: requirements
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          committer: qutebrowser bot <bot@qutebrowser.org>
          author: qutebrowser bot <bot@qutebrowser.org>
          token: ${{ secrets.QUTEBROWSER_BOT_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          body: |
            ## Changed files

            ${{ steps.requirements.outputs.changed }}

            ## Version updates

            ${{ steps.requirements.outputs.diff }}

            ---

            I'm a bot, bleep, bloop. :robot:

          branch: update-dependencies
