name: Recompile requirements

on:
  schedule:
    - cron: '10 10 * * *'
  issues:
  issue_comment:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Run recompile_requirements.py
        run: python3 scripts/dev/recompile_requirements.py
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          comitter: qutebrowser bot <bot@qutebrowser.org>
          author: qutebrowser bot <bot@qutebrowser.org>
          token: ${{ secrets.QUTEBROWSER_BOT_TOKEN }}
          commit-message: Update dependencies
          title: Update dependencies
          branch: update-dependencies
